### ISSUE TITLE
"Signature does not match request parameters." Error

### ISSUE THREAD

**Issue by BielRod** [crypto-crew-tech/cryptopia-api-python#14]
I am passing my api and secret keys to the api constructor, but when i perform a request im getting the error: "Signature does not match request parameters.".

Can you help me?

thanks for your time.
ps.: sorry about my english. i am just learning yet hahaha.

**Comment by danton721** [comment]
Please check my last pull request, and let me know if you still have problem.

**Comment by BielRod** [comment]
it worked , thanks! But my python version is 2.7.13 and i had to make a change on line 8:
from `from urlparse import urlparse` to `import urllib as urlparse`. After that little change the  request worked well. Thank you!

**Comment by scottydelta** [comment]
Still facing the same issue.
