### ISSUE TITLE
Signature does not match request parameters. Solution

### ISSUE THREAD

**Issue by trikota** [crypto-crew-tech/cryptopia-api-python#2]
Hi! Great lib, thanks!

It didn't work out of the box for me though.
Response for any method was
`{u'Success': False, u'Error': u'Signature does not match request parameters.'}`

And traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cryptopia.py", line 108, in get_balance
    post_parameters={'Currency': currency})
  File "cryptopia.py", line 44, in api_query
    if req['Message'] is None:
KeyError: 'Message'
```
The solution is to replace line 16 with
`self.secret = base64.b64decode(secret + '=' * (-len(secret) % 4))`

**Comment by saniales** [comment]
can you fork this repository, add your change and open a pr to me? so you can have all the credit for this discovery :)

**Comment by trikota** [comment]
I did that !
