### ISSUE TITLE
Sell order not being placed (TypeError)

### ISSUE THREAD

**Issue by kr0n0s1** [crypto-crew-tech/cryptopia-api-python#20]
When it tries to put a sell order this happens:

[+] Placing sell order at 0.00007758 (+100.0%)...
Traceback (most recent call last):
  File "pump-dump.py", line 142, in <module>
    COINS_OWNED, ERROR = API.get_balance(PUMP_COIN)[0]['Available']
TypeError: 'NoneType' object has no attribute '__getitem__'

Which I find strange because the buy order is working perfectly!

Thanks in advance.

**Comment by Neney22** [comment]
hey how did you got it working? i keep getting error 401
