### ISSUE TITLE
Getting 401 error running the script

### ISSUE THREAD

**Issue by Neney22** [crypto-crew-tech/cryptopia-api-python#21]
Status Code : 401 Client Error: Unauthorized for url: https://www.cryptopia.co.nz/Api/GetBalance

**Comment by Lord-of-Codes** [comment]
@Neney22 How did the issue get solved? Please tell me. I am having the same issue.

**Comment by saniales** [comment]
This issue and the other one connected are bad written, if problem persistes please file a new issue with a more detailed description
