### ISSUE TITLE
[HELP] Guide to install

### ISSUE THREAD

**Issue by JellyGummy** [crypto-crew-tech/cryptopia-api-python#22]
Hi guys any kind soul care to help listing the step to install? A brief one will do, thank you so much

**Comment by Haldon** [comment]
Linux installation:

Make sure you have at least Python 2.7.12 installed.

1. sudo su
2. mkdir cryptopia
3. cd cryptopia
4. vi cryptopia_api.py
5. copy the contents of https://github.com/crypto-crew-tech/cryptopia-api-python/blob/master/cryptopia_api.py in there
6. vi pump-dump.py
7. copy the contents of https://github.com/crypto-crew-tech/cryptopia-api-python/blob/master/examples/pump-dump/pump-dump.py in there
8. vi secrets.json
9. enter your api keys in there
10. run it by typing: python pump-dump.py

**Comment by JellyGummy** [comment]
Thank you so much buddy!

**Comment by JellyGummy** [comment]
hey bud may I know the enter API keys part do i use this format and paste it inside?
{
    "key" : "xxxxxxxxxxxxxxx",
    "secret" : "xxxxxxxxxxxxxxx"
}

**Comment by Haldon** [comment]
Yes just paste it instead of the xxxxx's

**Comment by saniales** [comment]
Very thanks to @Haldon
I am closing this issue and include it in the wiki section!

**Comment by cdoffx** [comment]
Can somebody help with running this app on a windows platform. Thanks

**Comment by saniales** [comment]
instructions are almost the same, make sure python 2 is  installed

**Comment by cdoffx** [comment]
Thanks @Saniales. After I installed python27 and ran pump-dump.py on the python.exe shell I got an error that stdin error line 1 invalid syntax. Please can you tell what is wrong?

**Comment by cdoffx** [comment]
@saniales. I have been able to run the script correctly but I got an error like this.
File "pump-dump.py", line 21, in (module) 
From cryptopia_api import Api
File " path\...cryptopia_api.py", line 9
import requests
ImportError: No module named requests.
What should I do

**Comment by saniales** [comment]
pip install requests will do the trick ;)

**Comment by saniales** [comment]
create a `secrets.json` file in the directory, then run the pump dump

**Comment by cdoffx** [comment]
I have it created already before running the pump-dump.py but that's the error it gives

**Comment by saniales** [comment]
This error either comes when json file does not exist or it's not properly formatted

**Comment by cdoffx** [comment]
Ermm I'm not sure about the formating. But I  just edited as it's in the downloaded zip
