### ISSUE TITLE
Signature does not match request parameters.

### ISSUE THREAD

**Issue by scottydelta** [crypto-crew-tech/cryptopia-api-python#26]
I get Error: Signature does not match request parameters. when I do [

    BALANCE_BTC, ERROR = API.get_balance('BTC')

[Link](https://github.com/crypto-crew-tech/cryptopia-api-python/blob/6582394f8a50f50ab1c07a3d647b2a31aeb95ea5/examples/pump-dump/pump-dump.py#L46)

**Comment by subhamagr** [comment]
Same here, could anyone resolve the issue?

**Comment by subhamagr** [comment]
Fixed the issue. Please consider pull request #27

**Comment by saniales** [comment]
Fixed by PR #27
