### ISSUE TITLE
the sleep timer is at 1. why?

### ISSUE THREAD

**Issue by kwhrh** [crypto-crew-tech/cryptopia-api-python#30]
do we have to have to make the code sleep for 1 second?
and why so?
if it is manditory which seems like it has some use to avoid mistakes: how can it be as little as possible?

code looks like this:
...
""" Performs a generic api request """
time.sleep(1)
...

Thankies.

**Comment by saniales** [comment]
the answer is simple, if you send too many requests to cryptopia servers they ban you

**Comment by Lord-of-Codes** [comment]
but the cryptopia private [API page](https://www.cryptopia.co.nz/Forum/Thread/256) suggests that a user can send upto 1000 requests per minute subject to a maximum of 1000000 requests per day.

**Comment by saniales** [comment]
we can remove the waiting value, it will be up to developers to choose when to stop
