### ISSUE TITLE
change line 50 in cryptopia api

### ISSUE THREAD

**Issue by stolencatkarma** [crypto-crew-tech/cryptopia-api-python#4]
https://github.com/crypto-crew-tech/cryptopia-api-python/blob/10554209e3cebb3d4efba4906b4bdb441dd2f248/cryptopia_api.py#L50

                           ) if get_parameters != None else "https://www.cryptopia.co.nz/Api/" + feature_requested + "/"

should be what line 50 is. because if you use an api feature with no parameters it returns "" for the url and errors out.

**Comment by saniales** [comment]
You can open a PR and submit your change after forking this repo :)

**Comment by saniales** [comment]
I checked the code and it's correct:
here lines 48-50:
```
url = "https://www.cryptopia.co.nz/Api/" + feature_requested + "/" + \
                  '/'.join(i for i in get_parameters.values()
                  ) if get_parameters != None else ""
```
now let's split the concats of strings and put parenthesis
```
url = ("https://www.cryptopia.co.nz/Api/") + \
        (feature_requested) + \
        ("/") + \
        ('/'.join(i for i in get_parameters.values()) if get_parameters != None else "")
```
as you can see only last part will be put to "" then this code is correct. Going to close this issue
