### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by hentr** [crypto-crew-tech/cryptopia-api-python#7]
I am trying to run the example:
```
from cryptopia_api import Api

api_wrapper = Api(key, sec)

#call a request to the api, like balance in BTC...
balance, error = api_wrapper.get_balance('BTC')
if error is not None:
    #handle error
    print('ERROR: %s' % error)
else:
    #ok
    print('Request successfull. Balance in BTC = %f' % balance)
```

But I just get: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-4bae04b70e34> in <module>()
      8 
      9 #call a request to the api, like balance in BTC...
---> 10 balance, error = api_wrapper.get_balance('BTC')
     11 if error is not None:
     12     #handle error

D:\Mega\Projects\Curreq\cryptopia_api.py in get_balance(self, currency)
    104         """ Gets the balance of the user in the specified currency """
    105         result, error = self.api_query(feature_requested='GetBalance',
--> 106                                        post_parameters={'Currency': currency})
    107         if error is None:
    108             result = result[0]

D:\Mega\Projects\Curreq\cryptopia_api.py in api_query(self, feature_requested, get_parameters, post_parameters)
     27             url = "https://www.cryptopia.co.nz/Api/" + feature_requested
     28             post_data = json.dumps(post_parameters)
---> 29             headers = self.secure_headers(url=url, post_data=post_data)
     30             req = requests.post(url, data=post_data, headers=headers)
     31             if req.status_code != 200:

D:\Mega\Projects\Curreq\cryptopia_api.py in secure_headers(self, url, post_data)
    169         nonce = str(int(time.time()))
    170         md5 = hashlib.md5()
--> 171         md5.update(post_data)
    172         rcb64 = base64.b64encode(md5.digest())
    173         signature = self.key + "POST" + \

TypeError: Unicode-objects must be encoded before hashing
```
And I have no idea what is going on, did not get very far with google either

**Comment by john-g123** [comment]
After a **ton** of trial and error, I figured out how to fix this.

change the secure_headers section to the following:

    def secure_headers(self, url, post_data):
        """ Creates secure header for cryptopia private api. """
        nonce = str(int(time.time()))
        md5 = hashlib.md5()
        md5.update(post_data.encode('utf-8'))
        rcb64 = base64.b64encode(md5.digest()).decode('utf-8')
        signature = self.key + "POST" + urllib.parse.quote_plus(url).lower() + nonce + rcb64
        sign = base64.b64encode(hmac.new(self.secret, signature.encode('utf-8'), hashlib.sha256).digest())
        header_value = "amx " + self.key + ":" + sign.decode('utf-8') + ":" + nonce
        return {'Authorization': header_value, 'Content-Type': 'application/json; charset=utf-8'}

**Comment by hentr** [comment]
ah, thanks! I was just now experimenting with how to do the encoding there in `secure_headers`. Thanks again for beating me to it :)

**Comment by saniales** [comment]
@john-g123 I would really appreciate if you send me a PR with the corrected code or drop a zip at thebotguy@protonmail.com :) I am closing this :)

**Comment by john-g123** [comment]
ah shit I just left work for the day and I was playing with it from that computer...I will do this tomorrow!
